import { LayoutDashboard, Briefcase, Mic2, Library, Scale, DollarSign, Wallet, Shield, Megaphone, MessageSquare, Users, Building2, Plane, Cpu, Target, AlertTriangle, CheckCircle2, Activity, Archive, BarChart3, UserCheck, Brain, FileText, Repeat, Clock, Send, ListChecks, CheckSquare, Flag, History, Disc, TrendingUp, AlertCircle, Link2, HeartHandshake, PiggyBank, CreditCard, FileCheck, Timer, Gauge, RefreshCw, ShoppingBag, Store, GraduationCap, Inbox, Bell, Zap, Globe, ServerCog, Database, Receipt, BookOpen, Calculator, Coins, ShieldCheck, Ligature as FileSignature } from 'lucide-react';
import type { ComponentType } from 'react';

export type AdminNavItem = {
  label: string;
  path: string;
  icon?: ComponentType<{ className?: string }>;
};

export type AdminNavSection = {
  key: string;
  label: string;
  icon: ComponentType<{ className?: string }>;
  color: string;
  items: AdminNavItem[];
};

export const ADMIN_NAV: AdminNavSection[] = [
  {
    key: 'command',
    label: 'Command Center',
    icon: LayoutDashboard,
    color: '#F59E0B',
    items: [
      { label: 'Executive Summary',      path: '/dashboard/admin-os',                       icon: LayoutDashboard },
      { label: 'Priorities',             path: '/dashboard/admin-os/priorities',            icon: Target         },
      { label: 'Risks + Blocks',         path: '/dashboard/admin-os/risks-blocks',          icon: AlertTriangle  },
      { label: 'Decisions Needed',       path: '/dashboard/admin-os/decisions',             icon: CheckCircle2   },
      { label: 'System Health',          path: '/dashboard/admin-os/system-health',         icon: Activity       },
      { label: 'Executive Digest Archive', path: '/dashboard/admin-os/digests',             icon: Archive        },
    ],
  },
  {
    key: 'projects',
    label: 'Project Operations',
    icon: Briefcase,
    color: '#06B6D4',
    items: [
      { label: 'All Projects Dashboard', path: '/dashboard/admin-os/projects',              icon: BarChart3      },
      { label: 'Project Progress',       path: '/dashboard/admin-os/projects/progress',     icon: Gauge          },
      { label: 'Worker Assignments',     path: '/dashboard/admin-os/projects/workers',      icon: UserCheck      },
      { label: 'Human Assignments',      path: '/dashboard/admin-os/projects/humans',       icon: Users          },
      { label: 'AI Agent Assignments',   path: '/dashboard/admin-os/projects/agents',       icon: Brain          },
      { label: 'Project Safe Admin',     path: '/dashboard/admin-os/projects/safes',        icon: ShieldCheck    },
      { label: 'Deliverables Tracking',  path: '/dashboard/admin-os/projects/deliverables', icon: ListChecks     },
      { label: 'Payment Approvals',      path: '/dashboard/admin-os/projects/payments',     icon: DollarSign     },
      { label: 'Delayed Payments',       path: '/dashboard/admin-os/projects/delayed',      icon: Clock          },
      { label: 'Project History',        path: '/dashboard/admin-os/projects/history',      icon: History        },
    ],
  },
  {
    key: 'artists',
    label: 'Artist Operations',
    icon: Mic2,
    color: '#EC4899',
    items: [
      { label: 'Active Artist Accounts', path: '/dashboard/admin-os/artists',               icon: Users          },
      { label: 'Artist Onboarding',      path: '/dashboard/admin-os/artists/onboarding',    icon: UserCheck      },
      { label: 'Release Readiness',      path: '/dashboard/admin-os/artists/releases',      icon: Disc           },
      { label: 'Campaign Controls',      path: '/dashboard/admin-os/artists/campaigns',     icon: Megaphone      },
      { label: 'Artist Contracts',       path: '/dashboard/admin-os/artists/contracts',     icon: FileText       },
      { label: 'Artist Wallet Oversight',path: '/dashboard/admin-os/artists/wallet',        icon: Wallet         },
      { label: 'Rep Activity',           path: '/dashboard/admin-os/artists/rep-activity',  icon: Activity       },
      { label: 'Issues + Escalations',   path: '/dashboard/admin-os/artists/escalations',   icon: AlertCircle    },
    ],
  },
  {
    key: 'catalog',
    label: 'Catalog Operations',
    icon: Library,
    color: '#10B981',
    items: [
      { label: 'Catalog Clients',        path: '/dashboard/admin-os/catalog',               icon: Users          },
      { label: 'Catalog Contracts',      path: '/dashboard/admin-os/catalog/contracts',     icon: FileText       },
      { label: 'Revenue + Payout Status',path: '/dashboard/admin-os/catalog/revenue',       icon: DollarSign     },
      { label: 'Asset + Metadata Health',path: '/dashboard/admin-os/catalog/metadata',      icon: Database       },
      { label: 'Campaign Activity',      path: '/dashboard/admin-os/catalog/campaigns',     icon: Megaphone      },
      { label: 'Catalog Worker Assignments', path: '/dashboard/admin-os/catalog/workers',   icon: UserCheck      },
    ],
  },
  {
    key: 'legal',
    label: 'Business Affairs + Legal',
    icon: Scale,
    color: '#06B6D4',
    items: [
      { label: 'LOIs',                   path: '/dashboard/admin-os/legal',                 icon: FileText       },
      { label: 'Contract Pipeline',      path: '/dashboard/admin-os/legal/pipeline',        icon: Link2          },
      { label: 'PandaDoc Loop',          path: '/dashboard/admin-os/legal/pandadoc',        icon: Repeat         },
      { label: 'Signed Contracts',       path: '/dashboard/admin-os/legal/signed',          icon: FileCheck      },
      { label: 'Renewals 90/60/30',      path: '/dashboard/admin-os/legal/renewals',        icon: RefreshCw      },
      { label: 'Notice Deadlines',       path: '/dashboard/admin-os/legal/notices',         icon: Timer          },
      { label: 'NDA / Project Contracts',path: '/dashboard/admin-os/legal/ndas',            icon: FileSignature  },
      { label: 'Legal Tasks',            path: '/dashboard/admin-os/legal/tasks',           icon: CheckSquare    },
      { label: 'Guidance Queue',         path: '/dashboard/admin-os/legal/guidance',        icon: MessageSquare  },
    ],
  },
  {
    key: 'finance',
    label: 'Finance + Accounting',
    icon: DollarSign,
    color: '#10B981',
    items: [
      { label: 'Accounting Command Center', path: '/dashboard/admin-os/finance',            icon: Calculator     },
      { label: 'Revenue Movement',       path: '/dashboard/admin-os/finance/revenue',       icon: TrendingUp     },
      { label: 'Expenses + Cash',        path: '/dashboard/admin-os/finance/expenses',      icon: Receipt        },
      { label: 'Payout Queue',           path: '/dashboard/admin-os/finance/payouts',       icon: Send           },
      { label: 'Royalty Reporting',      path: '/dashboard/admin-os/finance/royalties',     icon: BookOpen       },
      { label: 'Month-End Close',        path: '/dashboard/admin-os/finance/close',         icon: CheckCircle2   },
      { label: 'Tax Ready Status',       path: '/dashboard/admin-os/finance/tax',           icon: FileText       },
      { label: '1099 Tracking',          path: '/dashboard/admin-os/finance/1099',          icon: Flag           },
    ],
  },
  {
    key: 'banking',
    label: 'Banking + Capital',
    icon: Wallet,
    color: '#06B6D4',
    items: [
      { label: 'Banking Setup Status',   path: '/dashboard/admin-os/banking',               icon: PiggyBank      },
      { label: 'Reserve Planning',       path: '/dashboard/admin-os/banking/reserves',      icon: Database       },
      { label: 'Card Access Eligibility',path: '/dashboard/admin-os/banking/cards',         icon: CreditCard     },
      { label: 'Capital Readiness',      path: '/dashboard/admin-os/banking/capital',       icon: Coins          },
      { label: 'Funding Opportunities',  path: '/dashboard/admin-os/banking/funding',       icon: TrendingUp     },
      { label: 'Payment Routing',        path: '/dashboard/admin-os/banking/routing',       icon: Send           },
    ],
  },
  {
    key: 'risk',
    label: 'Risk + Protection',
    icon: Shield,
    color: '#F59E0B',
    items: [
      { label: 'Coverage Status',        path: '/dashboard/admin-os/risk',                  icon: ShieldCheck    },
      { label: 'Required Policies',      path: '/dashboard/admin-os/risk/policies',         icon: FileText       },
      { label: 'Renewals Due',           path: '/dashboard/admin-os/risk/renewals',         icon: RefreshCw      },
      { label: 'Coverage Gaps',          path: '/dashboard/admin-os/risk/gaps',             icon: AlertTriangle  },
      { label: 'Claims Routing',         path: '/dashboard/admin-os/risk/claims',           icon: Send           },
      { label: 'Live Event Risk',        path: '/dashboard/admin-os/risk/events',           icon: Zap            },
    ],
  },
  {
    key: 'marketing',
    label: 'Campaign + Marketing',
    icon: Megaphone,
    color: '#EC4899',
    items: [
      { label: 'AI Rep Campaign Controls', path: '/dashboard/admin-os/marketing',           icon: Brain          },
      { label: 'Human Marketing Overrides',path: '/dashboard/admin-os/marketing/overrides', icon: UserCheck      },
      { label: 'Budget Changes',         path: '/dashboard/admin-os/marketing/budgets',     icon: DollarSign     },
      { label: 'Add Campaign Actions',   path: '/dashboard/admin-os/marketing/actions',     icon: Zap            },
      { label: 'Performance Adjustments',path: '/dashboard/admin-os/marketing/performance', icon: BarChart3      },
      { label: 'Content Rollout',        path: '/dashboard/admin-os/marketing/rollout',     icon: Send           },
      { label: 'Release Calendar',       path: '/dashboard/admin-os/marketing/calendar',    icon: Disc           },
    ],
  },
  {
    key: 'comms',
    label: 'Communications Ops',
    icon: MessageSquare,
    color: '#06B6D4',
    items: [
      { label: 'Inbox Monitoring',       path: '/dashboard/admin-os/comms',                 icon: Inbox          },
      { label: 'Escalations Waiting',    path: '/dashboard/admin-os/comms/escalations',     icon: Bell           },
      { label: 'Auto Replies',           path: '/dashboard/admin-os/comms/auto',            icon: Repeat         },
      { label: 'Drip Campaigns',         path: '/dashboard/admin-os/comms/drips',           icon: Send           },
      { label: 'FAQ Learning Queue',     path: '/dashboard/admin-os/comms/faq',             icon: Brain          },
      { label: 'Slack / WhatsApp',       path: '/dashboard/admin-os/comms/messaging',       icon: MessageSquare  },
    ],
  },
  {
    key: 'people',
    label: 'People + Performance',
    icon: Users,
    color: '#F59E0B',
    items: [
      { label: 'Team Performance',       path: '/dashboard/admin-os/people',                icon: BarChart3      },
      { label: 'Workload + Capacity',    path: '/dashboard/admin-os/people/workload',       icon: Gauge          },
      { label: 'KPI Tracking',           path: '/dashboard/admin-os/people/kpis',           icon: TrendingUp     },
      { label: 'Blocked Team Members',   path: '/dashboard/admin-os/people/blocked',        icon: AlertCircle    },
      { label: 'Task Velocity',          path: '/dashboard/admin-os/people/velocity',       icon: Activity       },
      { label: 'Output by Person',       path: '/dashboard/admin-os/people/by-person',      icon: UserCheck      },
      { label: 'Output by Team',         path: '/dashboard/admin-os/people/by-team',        icon: Users          },
    ],
  },
  {
    key: 'partners',
    label: 'Partner Pipeline',
    icon: Building2,
    color: '#10B981',
    items: [
      { label: 'Banc of California',     path: '/dashboard/admin-os/partners',              icon: Building2      },
      { label: 'Gallagher',              path: '/dashboard/admin-os/partners/gallagher',    icon: Building2      },
      { label: 'Fractional Collective',  path: '/dashboard/admin-os/partners/fractional',   icon: HeartHandshake },
      { label: 'Future Institutional',   path: '/dashboard/admin-os/partners/future',       icon: Globe          },
      { label: 'Inquiry Tracking',       path: '/dashboard/admin-os/partners/inquiries',    icon: Inbox          },
      { label: 'Pending Docs',           path: '/dashboard/admin-os/partners/docs',         icon: FileText       },
      { label: 'Next Step Owner',        path: '/dashboard/admin-os/partners/owners',       icon: UserCheck      },
      { label: 'Package Match Status',   path: '/dashboard/admin-os/partners/match',        icon: CheckCircle2   },
    ],
  },
  {
    key: 'touring',
    label: 'Touring / Store / Campus',
    icon: Plane,
    color: '#EC4899',
    items: [
      { label: 'Tour Manager Ops',       path: '/dashboard/admin-os/touring',               icon: Plane          },
      { label: 'Store Manager Ops',      path: '/dashboard/admin-os/touring/store',         icon: Store          },
      { label: 'Campus Program Ops',     path: '/dashboard/admin-os/touring/campus',        icon: GraduationCap  },
      { label: 'Membership Billing',     path: '/dashboard/admin-os/touring/membership',    icon: CreditCard     },
      { label: 'Support Tickets',        path: '/dashboard/admin-os/touring/support',       icon: MessageSquare  },
      { label: 'Inventory / Merch',      path: '/dashboard/admin-os/touring/inventory',     icon: ShoppingBag    },
    ],
  },
  {
    key: 'agents',
    label: 'AI Agent Roster',
    icon: Cpu,
    color: '#06B6D4',
    items: [
      { label: 'All Agents',             path: '/dashboard/admin-os/agents',                icon: ServerCog      },
      { label: 'Agent Categories',       path: '/dashboard/admin-os/agents/categories',     icon: Brain          },
      { label: 'Agent Assignments',      path: '/dashboard/admin-os/agents/assignments',    icon: Target         },
      { label: 'Agent Activity Log',     path: '/dashboard/admin-os/agents/activity',       icon: Activity       },
      { label: 'Ledger',                 path: '/dashboard/admin-os/agents/ledger',         icon: DollarSign     },
      { label: 'Vault',                  path: '/dashboard/admin-os/agents/vault',          icon: Wallet         },
      { label: 'Shield',                 path: '/dashboard/admin-os/agents/shield',         icon: Shield         },
      { label: 'Beacon',                 path: '/dashboard/admin-os/agents/beacon',         icon: Activity       },
      { label: 'Stage',                  path: '/dashboard/admin-os/agents/stage',          icon: Disc           },
      { label: 'SignalOps',              path: '/dashboard/admin-os/agents/signalops',      icon: BarChart3      },
      { label: 'Crest',                  path: '/dashboard/admin-os/agents/crest',          icon: HeartHandshake },
      { label: 'Anchor',                 path: '/dashboard/admin-os/agents/anchor',         icon: ShieldCheck    },
      { label: 'Paula Exec Assistant',   path: '/dashboard/admin-os/agents/paula-exec',     icon: UserCheck      },
      { label: 'Jacquelyn Exec Support', path: '/dashboard/admin-os/agents/jacquelyn-exec', icon: UserCheck      },
      { label: 'Counsel',                path: '/dashboard/admin-os/agents/counsel',        icon: Scale          },
      { label: 'Contract Loop Manager',  path: '/dashboard/admin-os/agents/contract-loop',  icon: Repeat         },
      { label: 'Industry Marketing Rep', path: '/dashboard/admin-os/agents/industry-marketing', icon: Megaphone  },
      { label: 'Tour Manager Rep',       path: '/dashboard/admin-os/agents/tour-manager',   icon: Plane          },
      { label: 'Store Manager Rep',      path: '/dashboard/admin-os/agents/store-manager',  icon: Store          },
      { label: 'Campus Manager',         path: '/dashboard/admin-os/agents/campus-manager', icon: GraduationCap  },
      { label: 'Artist Account Manager', path: '/dashboard/admin-os/agents/artist-account', icon: Mic2           },
      { label: 'Label Account Manager',  path: '/dashboard/admin-os/agents/label-account',  icon: Library        },
    ],
  },
];
